apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: motebehov-microfrontend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  tokenx:
    enabled: true
  image: {{ image }}
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  accessPolicy:
    inbound:
      rules:
        - application: tms-min-side
          namespace: min-side
    outbound:
      rules:
        - application: syfomotebehov
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "20m"
      memory: 128Mi
  env:
    - name: SYFOMOTEBEHOV_BACKEND_HOST
      value: "http://syfomotebehov"
    - name: SYFOMOTEBEHOV_CLIENT_ID
      value: dev-gcp:team-esyfo:syfomotebehov
    - name: MOTEBEHOV_URL
      value: "https://www.ekstern.dev.nav.no/syk/dialogmoter/sykmeldt"
