apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aktivitetskrav-microfrontend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  prometheus:
    enabled: true
    path: /api/internal/metrics
  tokenx:
    enabled: true
  image: {{ image }}
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  accessPolicy:
    inbound:
      rules:
        - application: tms-min-side
          namespace: min-side
    outbound:
      rules:
        - application: aktivitetskrav-backend
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "20m"
      memory: 128Mi
  env:
    - name: AKTIVITETSKRAV_BACKEND_HOST
      value: "http://aktivitetskrav-backend"
    - name: AKTIVITETSKRAV_CLIENT_ID
      value: "prod-gcp:team-esyfo:aktivitetskrav-backend"
    - name: AKTIVITETSKRAV_URL
      value: "https://www.nav.no/syk/aktivitetskrav"
