version: 2

registries:
  github-npm:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.READER_TOKEN }}

updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - github-npm
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    groups:
      navikt:
        patterns:
          - "@navikt/*"
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    groups:
      actions:
        patterns:
          - "*"
