packages:
  - "microfrontends/*"
  - "packages/*"

saveExact: true
minimumReleaseAge: 4320
blockExoticSubdeps: true

allowBuilds:
  esbuild: true
  sharp: true
  lefthook: false

overrides:
  yaml: 2.8.3
