apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dialogmote-microfrontend # Change this to your application name
  namespace: team-esyfo # Change this to your namespace
  labels:
    team: team-esyfo # Change this to your team name
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  tokenx:
    enabled: true
  image: {{ image }}
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  accessPolicy:
    inbound:
      rules:
        - application: tms-min-side
          namespace: min-side
    outbound:
      rules:
        - application: isdialogmote
          namespace: teamsykefravr
        - application: syfomotebehov
          namespace: team-esyfo
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "20m"
      memory: 128Mi
  env: # Add your environment variables here
    - name: ISDIALOGMOTE_API_URL
      value: "http://isdialogmote.teamsykefravr/api/v2/arbeidstaker/brev"
    - name: ISDIALOGMOTE_CLIENT_ID
      value: prod-gcp:teamsykefravr:isdialogmote
    - name: SYFOMOTEBEHOV_API_URL
      value: "http://syfomotebehov.team-esyfo/syfomotebehov/api/v4/arbeidstaker/motebehov"
    - name: SYFOMOTEBEHOV_CLIENT_ID
      value: prod-gcp:team-esyfo:syfomotebehov
    - name: DIALOGMOTE_URL
      value: "https://www.nav.no/syk/dialogmoter/sykmeldt"
