name: Deploy aktivitetskrav

on:
  push:
    branches:
      - "main"
    paths:
      - "microfrontends/aktivitetskrav/**"
      - "packages/shared/**"
      - ".github/workflows/deploy-aktivitetskrav.yaml"
      - ".github/workflows/deploy-microfrontend-reusable.yml"
      - "pnpm-lock.yaml"
      - "package.json"
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy-microfrontend-reusable.yml
    with:
      microfrontend_name: "aktivitetskrav"
      build_script: "build:aktivitetskrav-microfrontend"
      dockerfile: "./microfrontends/aktivitetskrav/Dockerfile"
      cdn_source: "./microfrontends/aktivitetskrav/dist/client/_astro"
      manifest_id: "syfo-aktivitetskrav"
      application_name: "aktivitetskrav-microfrontend"
      dev_manifest_url: "http://aktivitetskrav-microfrontend.team-esyfo"
      dev_resource: "microfrontends/aktivitetskrav/nais/dev-gcp/nais.yaml"
      enable_prod: false
    secrets: inherit
