name: Deploy motebehov

on:
  push:
    branches:
      - "main"
      - "deploy-motebehov"
    paths:
      - "microfrontends/motebehov/**"
      - "pnpm-lock.yaml"
      - "package.json"

jobs:
  deploy:
    uses: ./.github/workflows/deploy-microfrontend-reusable.yml
    with:
      microfrontend_name: "motebehov"
      build_script: "build:motebehov-microfrontend"
      dockerfile: "./microfrontends/motebehov/Dockerfile"
      cdn_source: "./microfrontends/motebehov/dist/client/_astro"
      manifest_id: "syfo-motebehov"
      application_name: "motebehov-microfrontend"
      dev_manifest_url: "http://motebehov-microfrontend.min-side"
      dev_resource: "microfrontends/motebehov/nais/dev-gcp/nais.yaml"
      enable_prod: false
    secrets: inherit
