name: Deploy aktivitetskrav

on:
  push:
    branches:
      - "main"
    paths:
      - "microfrontends/aktivitetskrav/**"
      - "packages/shared/**"
      - ".github/workflows/deploy-aktivitetskrav.yaml"
      - ".github/workflows/deploy-microfrontend-reusable.yml"
      - "pnpm-lock.yaml"
      - "package.json"
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy-microfrontend-reusable.yml
    with:
      microfrontend_name: "aktivitetskrav"
      manifest_id: "syfo-aktivitetskrav"
      enable_prod: true
    secrets: inherit
