name: Deploy dialogmote

on:
  push:
    branches:
      - "main"
    paths:
      - "microfrontends/dialogmote/**"
      - "packages/shared/**"
      - ".github/workflows/deploy-dialogmote.yaml"
      - ".github/workflows/deploy-microfrontend-reusable.yml"
      - "pnpm-lock.yaml"
      - "package.json"
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy-microfrontend-reusable.yml
    with:
      microfrontend_name: "dialogmote"
      build_script: "build:dialogmote-microfrontend"
      dockerfile: "./microfrontends/dialogmote/Dockerfile"
      cdn_source: "./microfrontends/dialogmote/dist/client/_astro"
      manifest_id: "syfo-dialog"
      application_name: "dialogmote-microfrontend"
      dev_manifest_url: "http://dialogmote-microfrontend.team-esyfo"
      dev_resource: "microfrontends/dialogmote/nais/dev-gcp/nais.yaml"
      enable_prod: false
    secrets: inherit
