name: "Deploy dev&prod"
on:
  push:
    branches:
      - "main"
      - "deploy-motebehov"
    paths:
      - "microfrontends/motebehov/**"
      - "pnpm-lock.yaml"
      - "package.json"

jobs:
  build:
    name: "build"
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"

    steps:
      - uses: "actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd" # v5
      - uses: "pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320" # v4
      - uses: "actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444" # v5
        with:
          node-version: 24
          registry-url: "https://npm.pkg.github.com"
          cache: "pnpm"

      - name: "Install dependencies"
        run: "pnpm install --frozen-lockfile"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: "Run tests"
        run: "pnpm test"

      - name: "Build application"
        run: "pnpm run build:motebehov-microfrontend"

      - name: "Upload to cdn"
        uses: "nais/deploy/actions/cdn-upload/v2@437e4adfe270e3f1c98fd0eed7f86ecf0e0873db" # master
        with:
          team: team-esyfo # Change this to your team name
          source: ./microfrontends/motebehov/dist/client/_astro
          destination: "motebehov-microfrontend" # Change this to your application name

      - name: "Build and push"
        uses: "nais/docker-build-push@078e460885ed0424b60d45ce9220b4be1748be9d" # v0
        id: docker-build-push
        with:
          team: team-esyfo # Change this to your team name
          dockerfile: ./microfrontends/motebehov/Dockerfile

    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  update-manifest-dev:
    permissions:
      contents: "read"
      id-token: "write"
    uses: "navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest-v3.yaml@67dc876fb9e1a0b115e47a36fd46a1c7b0064d4c" # main
    needs: build
    with:
      id: "syfo-motebehov" # Change this to your microfrontend id.
      url: "http://motebehov-microfrontend.min-side" # Change the url to contain your application name. Example: http://my-app.namespace
      appname: "motebehov-microfrontend" # Change this to your application name
      namespace: "team-esyfo" # Change this to your namespace
      cluster: dev-gcp
      commitmsg: ${{ github.event.head_commit.message}}
      fallback: "fallback" # Should containt the path to the fallback page after src/pages/[locale]/... Only needs to be changed if you move the fallback in the pages structure
      ssr: true
    secrets: inherit

  # update-manifest-prod:
  #   if: github.ref == 'refs/heads/main'
  #   uses: "navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest-v3.yaml@67dc876fb9e1a0b115e47a36fd46a1c7b0064d4c" # main
  #   needs: build
  #   with:
  #     id: "syfo-dialog"
  #     url: "http://tms-microfrontend-template-ssr.min-side"
  #     appname: "tms-microfrontend-template-ssr"
  #     namespace: "team-namespace"
  #     cluster: prod-gcp
  #     commitmsg: ${{ github.event.head_commit.message}}
  #     fallback: "fallback" # Should containt the path to the fallback page after src/pages/[locale]/...
  #     ssr: true
  #   secrets: inherit

  deploy-dev:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"
    needs: [build, update-manifest-dev]
    steps:
      - uses: "actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5" # v4
      - name: "Deploy to dev"
        uses: "nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1" # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: microfrontends/motebehov/nais/dev-gcp/nais.yaml
          VAR: image=${{ needs.build.outputs.image }},version=${{ github.sha }}

  # deploy-prod:
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: "ubuntu-latest"
  #   permissions:
  #     contents: "read"
  #     id-token: "write"
  #   needs: [build, update-manifest-prod]

  #   steps:
  #     - uses: "actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5" # v4
  #     - name: "Deploy to prod"
  #       uses: "nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1" # v2
  #       env:
  #         CLUSTER: prod-gcp
  #         RESOURCE: microfrontends/dialogmote/nais/prod-gcp/nais.yaml
  #         VAR: image=${{ needs.build.outputs.image }},version=${{ github.sha }}
