name: Deploy meroppfolging

on:
  push:
    branches:
      - "main"
    paths:
      - "microfrontends/meroppfolging/**"
      - "packages/shared/**"
      - ".github/workflows/deploy-meroppfolging.yaml"
      - ".github/workflows/deploy-microfrontend-reusable.yml"
      - "pnpm-lock.yaml"
      - "package.json"
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy-microfrontend-reusable.yml
    with:
      microfrontend_name: "meroppfolging"
      manifest_id: "syfo-meroppfolging"
      enable_prod: true
    secrets: inherit
