name: Main CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Reusable CI
    uses: ./.github/workflows/ci-reusable.yml
